# Minimal CppDeps-compatible resolver used by SyLog.
#
# There are no optional fallbacks here: every dependency declared with
# cppdeps_add() is mandatory. Some upstream projects, however, do not expose a
# modern CMake target from their build tree. In that case the dependency
# manifest must declare an explicit BUILD recipe/BUILD_TARGET, and SyLog creates
# the requested namespaced target from the resolved dependency source.

include(FetchContent)

set_property(GLOBAL PROPERTY SYLOG_CPPDEPS_NAMES "")

function(cppdeps_add)
  cmake_parse_arguments(ARG "" "NAME;PROVIDES;GIT_REPOSITORY;TAG;BUILD;BUILD_TARGET" "" ${ARGN})

  if(NOT ARG_NAME)
    message(FATAL_ERROR "cppdeps_add requires NAME")
  endif()
  if(NOT ARG_PROVIDES)
    message(FATAL_ERROR "cppdeps_add(${ARG_NAME}) requires PROVIDES")
  endif()
  if(NOT ARG_GIT_REPOSITORY)
    message(FATAL_ERROR "cppdeps_add(${ARG_NAME}) requires GIT_REPOSITORY")
  endif()
  if(NOT ARG_TAG)
    message(FATAL_ERROR "cppdeps_add(${ARG_NAME}) requires TAG")
  endif()
  if(NOT ARG_BUILD)
    set(ARG_BUILD CMAKE_ADD_SUBDIRECTORY)
  endif()

  set(prefix "SYLOG_CPPDEP_${ARG_NAME}")
  set_property(GLOBAL APPEND PROPERTY SYLOG_CPPDEPS_NAMES "${ARG_NAME}")
  set_property(GLOBAL PROPERTY "${prefix}_PROVIDES" "${ARG_PROVIDES}")
  set_property(GLOBAL PROPERTY "${prefix}_GIT_REPOSITORY" "${ARG_GIT_REPOSITORY}")
  set_property(GLOBAL PROPERTY "${prefix}_TAG" "${ARG_TAG}")
  set_property(GLOBAL PROPERTY "${prefix}_BUILD" "${ARG_BUILD}")
  set_property(GLOBAL PROPERTY "${prefix}_BUILD_TARGET" "${ARG_BUILD_TARGET}")
endfunction()

function(_sylog_cppdeps_make_alias provides target_name dep_name)
  if(TARGET ${provides})
    return()
  endif()
  if(NOT TARGET ${target_name})
    message(FATAL_ERROR
      "Dependency '${dep_name}' expected build-tree target '${target_name}', "
      "but it was not created.")
  endif()
  add_library(${provides} ALIAS ${target_name})
endfunction()

function(_sylog_cppdeps_make_cpptest provides source_dir dep_name)
  if(TARGET ${provides})
    return()
  endif()

  set(config_dir "${CMAKE_BINARY_DIR}/_deps/sylog_cpptest_config")
  file(MAKE_DIRECTORY "${config_dir}")
  file(WRITE "${config_dir}/config.h"
    "// Generated by SyLog CppDeps integration\n\n"
    "#pragma once\n\n"
    "#define HAVE_SSTREAM 1\n"
    "#define HAVE_SNPRINTF 1\n")
  file(WRITE "${config_dir}/winconfig.h"
    "// Generated by SyLog CppDeps integration\n\n"
    "#pragma once\n\n"
    "#include \"config.h\"\n")

  file(GLOB_RECURSE cpptest_patch_files
    "${source_dir}/src/*.h"
    "${source_dir}/src/*.cpp")
  foreach(f IN LISTS cpptest_patch_files)
    file(READ "${f}" txt)
    string(REPLACE "std::auto_ptr" "std::unique_ptr" txt "${txt}")
    string(REPLACE "auto_ptr<" "unique_ptr<" txt "${txt}")
    file(WRITE "${f}" "${txt}")
  endforeach()

  add_library(sylog_cpptest STATIC
    "${source_dir}/src/collectoroutput.cpp"
    "${source_dir}/src/compileroutput.cpp"
    "${source_dir}/src/htmloutput.cpp"
    "${source_dir}/src/missing.cpp"
    "${source_dir}/src/source.cpp"
    "${source_dir}/src/suite.cpp"
    "${source_dir}/src/textoutput.cpp"
    "${source_dir}/src/time.cpp"
    "${source_dir}/src/utils.cpp"
  )

  target_include_directories(sylog_cpptest PUBLIC
    "${source_dir}/src"
    "${config_dir}")
  target_compile_features(sylog_cpptest PUBLIC cxx_std_11)
  target_compile_definitions(sylog_cpptest PRIVATE HAVE_CONFIG_H=1)

  add_library(${provides} ALIAS sylog_cpptest)
endfunction()

function(cppdeps_install_all)
  cmake_parse_arguments(ARG "WRITE_LOCKFILE" "" "" ${ARGN})

  get_property(names GLOBAL PROPERTY SYLOG_CPPDEPS_NAMES)
  if(NOT names)
    message(FATAL_ERROR "cppdeps_install_all called but no dependencies were declared")
  endif()

  set(lock_contents "# Generated by SyLog's mandatory cppdeps resolver.\n")

  foreach(name IN LISTS names)
    set(prefix "SYLOG_CPPDEP_${name}")
    get_property(provides GLOBAL PROPERTY "${prefix}_PROVIDES")
    get_property(repo GLOBAL PROPERTY "${prefix}_GIT_REPOSITORY")
    get_property(tag GLOBAL PROPERTY "${prefix}_TAG")
    get_property(build GLOBAL PROPERTY "${prefix}_BUILD")
    get_property(build_target GLOBAL PROPERTY "${prefix}_BUILD_TARGET")

    if(TARGET ${provides})
      string(APPEND lock_contents "${name} ${provides} ${repo} ${tag} already-provided\n")
      continue()
    endif()

    message(STATUS "Resolving mandatory dependency ${name} from ${repo} (${tag})")

    if(build STREQUAL "CPPTST_STATIC")
      FetchContent_Declare(${name}
        GIT_REPOSITORY ${repo}
        GIT_TAG        ${tag}
        GIT_SHALLOW    TRUE
        SOURCE_SUBDIR  __sylog_no_cmake_subdir__
      )
      FetchContent_MakeAvailable(${name})
      FetchContent_GetProperties(${name} SOURCE_DIR source_dir)
      _sylog_cppdeps_make_cpptest(${provides} "${source_dir}" "${name}")
    elseif(build STREQUAL "HEADER_ONLY")
      FetchContent_Declare(${name}
        GIT_REPOSITORY ${repo}
        GIT_TAG        ${tag}
        GIT_SHALLOW    TRUE
      )
      FetchContent_MakeAvailable(${name})
      if(NOT TARGET ${provides})
        FetchContent_GetProperties(${name} SOURCE_DIR source_dir)
        if(EXISTS "${source_dir}/include")
          add_library(${name}_header_only INTERFACE)
          target_include_directories(${name}_header_only INTERFACE "${source_dir}/include")
          target_compile_features(${name}_header_only INTERFACE cxx_std_20)
          add_library(${provides} ALIAS ${name}_header_only)
        endif()
      endif()
    else()
      FetchContent_Declare(${name}
        GIT_REPOSITORY ${repo}
        GIT_TAG        ${tag}
        GIT_SHALLOW    TRUE
      )
      FetchContent_MakeAvailable(${name})
    endif()

    if(NOT TARGET ${provides} AND build_target)
      _sylog_cppdeps_make_alias(${provides} ${build_target} ${name})
    endif()

    # If no explicit build target was provided, allow the two common modern CMake
    # cases: installed namespaced target already exists, or build-tree target is
    # the leaf name / dependency name. Anything else is an error and must be
    # declared explicitly in deps.cmake.
    if(NOT TARGET ${provides})
      set(candidate_targets "")
      if(provides MATCHES "::")
        string(REGEX REPLACE "^.*::" "" provided_leaf "${provides}")
        list(APPEND candidate_targets "${provided_leaf}")
      endif()
      list(APPEND candidate_targets "${name}")

      foreach(candidate IN LISTS candidate_targets)
        if(TARGET ${candidate} AND NOT TARGET ${provides})
          add_library(${provides} ALIAS ${candidate})
        endif()
      endforeach()
    endif()

    if(NOT TARGET ${provides})
      message(FATAL_ERROR
        "Dependency '${name}' was resolved, but required target '${provides}' was not created. "
        "Declare BUILD_TARGET for CMake dependencies or a supported BUILD recipe in deps.cmake.")
    endif()

    string(APPEND lock_contents "${name} ${provides} ${repo} ${tag}\n")
  endforeach()

  if(ARG_WRITE_LOCKFILE)
    file(WRITE "${CMAKE_BINARY_DIR}/cppdeps.lock" "${lock_contents}")
  endif()
endfunction()
